import Head from "next/head";
import { Categories } from "../components/Categories/Categories";
import Header from "../components/Header/Header";
import { Carousel } from "../components/Hero/Carousel";
import { Hero } from "../components/Hero/Hero";

export default function Home() {
  // Popular product categories 
  const PopularProductCategories = [
    {
      id: 1,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/multiple-devices.png",
        width: 40,
        height: 40,
      },
    },
    {
      id: 2,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/profile.png",
        width: 36,
        height: 36,
      },
    },
    {
      id: 3,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/dress.png",
        width: 30,
        height: 30,
      },
    },
    {
      id: 4,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/gift.png",
        width: 31,
        height: 31,
      },
    },
    {
      id: 5,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/profile.png",
        width: 36,
        height: 36,
      },
    },
    {
      id: 6,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/shopping-basket.png",
        width: 38,
        height: 38,
      },
    },
    {
      id: 7,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/laptop.png",
        width: 37,
        height: 37,
      },
    },
    {
      id: 8,
      title: "Electronics Appliances",
      image: {
        src: "/categories-icons/food.png",
        width: 40,
        height: 40,
      },
    },
  ];
  return (
    <>
      <Head>
        <title>Walcart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <section id="header">
          <Header />
        </section>
        <section id="hero">
          <Hero />
        </section>
        <section id="popular-category">
          <Categories title="Popular Product Categories" categories={PopularProductCategories} />
        </section>
      </main>
    </>
  );
}
